#!/usr/bin/env bash
#
# Build Surge XT's REAL GUI to WebAssembly.
#
# This compiles SurgeGUIEditor and its whole widget tree -- the same code the
# desktop plugin runs -- against JUCE's software rasterizer and the browser
# ComponentPeer in host/surge_wasm/. The output paints Surge's own pixels into a
# buffer that JS blits to a <canvas>.
#
# Run ./setup.sh and ./build.sh first: this links against libsurge-common.a and
# reads the include/define set out of that build tree.
#
#   ./build_gui.sh          incremental
#   ./build_gui.sh clean    recompile everything
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$REPO_ROOT"

EMSDK_DIR="$REPO_ROOT/emsdk"
SURGE="$REPO_ROOT/vendor/surge"
ENGINE_BUILD="$REPO_ROOT/build/wasm"
OBJ_DIR="$REPO_ROOT/build/gui-obj"
GEN_DIR="$REPO_ROOT/build/generated"
OUT="$REPO_ROOT/src/js/surge-gui.js"

log() { printf '\n\033[1;36m==> %s\033[0m\n' "$*"; }
die() { printf '\n\033[1;31mERROR: %s\033[0m\n' "$*" >&2; exit 1; }

[ -f "$ENGINE_BUILD/build.ninja" ] || die "Engine build tree missing. Run ./build.sh first."
[ -f "$ENGINE_BUILD/src/common/libsurge-common.a" ] || die "libsurge-common.a missing. Run ./build.sh"

# shellcheck disable=SC1091
source "$EMSDK_DIR/emsdk_env.sh" >/dev/null 2>&1
command -v emcc >/dev/null 2>&1 || die "emcc not on PATH"

[ "${1:-}" = "clean" ] && rm -rf "$OBJ_DIR"
mkdir -p "$OBJ_DIR" "$GEN_DIR" "$(dirname "$OUT")"

# Surge's embedded fonts and skin SVGs. Generated rather than produced by
# juce_add_binary_data, which needs the native juceaide helper and only exists
# inside the plugin target we do not build. See the tool for the full rationale.
log "Generating embedded resources"
uv run "$REPO_ROOT/tools/gen_binary_data.py"

# Reuse the exact include and define set CMake computed for the engine, so the
# GUI and the engine agree on every ABI-affecting macro (SURGE_COMPILE_BLOCK_SIZE
# above all).
NINJA="$ENGINE_BUILD/build.ninja"
INCLUDES="$(grep -m1 '^  INCLUDES = .*surge/src/common' "$NINJA" | sed 's/^  INCLUDES = //')"
DEFINES="$(awk '/surge-common\.dir\/SurgeSynthesizer\.cpp\.o:/{f=1} f && /^  DEFINES =/{print substr($0,13); exit}' "$NINJA")"
[ -n "$INCLUDES" ] && [ -n "$DEFINES" ] || die "Could not read flags from $NINJA"

# JUCE's global config header. JUCE refuses to compile without one, and the
# JucePlugin_* values are what juce_add_plugin would normally generate.
cat > "$GEN_DIR/AppConfig.h" <<'EOF'
/* GENERATED by build_gui.sh -- do not edit. */
#pragma once
#define JUCE_GLOBAL_MODULE_SETTINGS_INCLUDED 1
#define JUCE_STANDALONE_APPLICATION 0

#define JUCE_MODULE_AVAILABLE_juce_core             1
#define JUCE_MODULE_AVAILABLE_juce_events           1
#define JUCE_MODULE_AVAILABLE_juce_graphics         1
#define JUCE_MODULE_AVAILABLE_juce_data_structures  1
#define JUCE_MODULE_AVAILABLE_juce_gui_basics       1
#define JUCE_MODULE_AVAILABLE_juce_gui_extra        1
#define JUCE_MODULE_AVAILABLE_juce_audio_basics     1
#define JUCE_MODULE_AVAILABLE_juce_audio_processors_headless 1
#define JUCE_MODULE_AVAILABLE_juce_audio_processors 1
#define JUCE_MODULE_AVAILABLE_juce_dsp               1
#define JUCE_MODULE_AVAILABLE_juce_audio_utils      1
#define JUCE_MODULE_AVAILABLE_juce_osc              1
#define JUCE_MODULE_AVAILABLE_juce_audio_formats    1
#define JUCE_MODULE_AVAILABLE_juce_audio_devices    1

#define JUCE_USE_CURL           0
#define JUCE_WEB_BROWSER        0
#define JUCE_USE_XRANDR         0
#define JUCE_USE_XINERAMA       0
#define JUCE_USE_XSHM           0
#define JUCE_USE_XCURSOR        0
#define JUCE_USE_XRENDER        0
#define JUCE_USE_FREETYPE       1
#define JUCE_MODAL_LOOPS_PERMITTED 0

/* juce_add_plugin normally generates these; SurgeSynthProcessor reads them for
   its reported identity even though the browser, not a DAW, is the host. */
#define JucePlugin_Name                 "Surge XT"
#define JucePlugin_Desc                 "Surge XT"
#define JucePlugin_Manufacturer         "Surge Synth Team"
#define JucePlugin_ManufacturerCode     0x56736e74
#define JucePlugin_PluginCode           0x53757278
#define JucePlugin_VersionString        "1.4.0"
#define JucePlugin_VersionCode          0x10400
#define JucePlugin_IsSynth              1
#define JucePlugin_WantsMidiInput       1
#define JucePlugin_ProducesMidiOutput   1
#define JucePlugin_IsMidiEffect         0
#define JucePlugin_EditorRequiresKeyboardFocus 0
#define JucePlugin_MaxNumInputChannels  2
#define JucePlugin_MaxNumOutputChannels 2
EOF

SIMD="-msimd128 -msse4.2"
EXC="-fwasm-exceptions"

CXXFLAGS=(
    -std=c++20 -fno-char8_t -O2 -Wno-everything
    $SIMD $EXC
    -sUSE_FREETYPE=1
    -include "$GEN_DIR/AppConfig.h"
    -I"$GEN_DIR" -I"$REPO_ROOT/host"
    -I"$SURGE/libs/JUCE/modules"
    -I"$SURGE/src/surge-xt"
    -I"$SURGE/src/surge-xt/gui"
    -I"$SURGE/src/surge-xt/gui/widgets"
    -I"$SURGE/src/surge-xt/gui/overlays"
)

# Compile one source to $OBJ_DIR, skipping when the object is newer.
compile() {
    # Two statements on purpose: `local a=1 b=$a` expands every argument before
    # any assignment happens, so a single declaration would see $src unset and
    # die under `set -u`.
    local src="$1"
    local obj="$OBJ_DIR/$(echo "${src#"$REPO_ROOT"/}" | tr '/' '_').o"
    if [ -f "$obj" ] && [ "$obj" -nt "$src" ]; then
        echo "$obj"
        return
    fi
    em++ "${CXXFLAGS[@]}" $DEFINES $INCLUDES -c "$src" -o "$obj" \
        || die "Failed to compile $src"
    echo "$obj"
}

# Build the full source list first, then compile it in parallel. These are big
# JUCE and Surge translation units at -O2; serially this takes the better part
# of an hour, and they are completely independent of one another.
SOURCES=()

for m in juce_core juce_events juce_data_structures juce_graphics juce_gui_basics juce_gui_extra \
         juce_audio_basics juce_audio_processors_headless juce_audio_processors juce_dsp juce_audio_formats juce_audio_utils juce_osc; do
    unit="$GEN_DIR/unit_$m.cpp"
    printf '#include <%s/%s.cpp>\n' "$m" "$m" > "$unit"
    SOURCES+=("$unit")
done

# JUCE 8 ships HarfBuzz (text shaping) and SheenBidi (bidirectional text) as
# separate translation units rather than folding them into juce_graphics.cpp.
# Without them the link fails on hb_font_get_face and SBCodepointGetScript, and
# no text would render at all.
SOURCES+=("$SURGE/libs/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.cpp")
SOURCES+=("$SURGE/libs/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.c")

SOURCES+=("$GEN_DIR/SurgeXTBinary.cpp")

while IFS= read -r f; do
    # Windows-only; Surge's CMake excludes it per platform.
    case "$f" in *AccessibleAnnouncementWin.cpp) continue ;; esac
    SOURCES+=("$f")
done < <(find "$SURGE/src/surge-xt/gui" -name '*.cpp' | sort)

SOURCES+=("$SURGE/src/surge-xt/SurgeSynthEditor.cpp")
SOURCES+=("$SURGE/src/surge-xt/SurgeSynthProcessor.cpp")
# The editor references these directly: the Lua syntax highlighter used by the
# formula/wavetable editors, and the OSC settings overlay. They live outside
# gui/ so the find above misses them.
SOURCES+=("$SURGE/src/surge-xt/util/LuaTokeniserSurge.cpp")
SOURCES+=("$SURGE/src/surge-xt/osc/OpenSoundControl.cpp")
SOURCES+=("$REPO_ROOT/host/surge_gui_host.cpp")

# Exported so the subshells xargs spawns can see them.
export OBJ_DIR REPO_ROOT DEFINES INCLUDES
export CXXFLAGS_STR="${CXXFLAGS[*]}"

JOBS="$(nproc 2>/dev/null || echo 4)"
log "Compiling ${#SOURCES[@]} translation units, $JOBS at a time"

# SheenBidi's JUCE wrapper pulls in juce_core headers for warning pragmas, so it
# needs both the module search path and the AppConfig force-include (JUCE errors
# out with "No global header file was included!" otherwise) -- even though the
# file itself is plain C. AppConfig.h is only #defines, so C is fine with it.
export CFLAGS_STR="$SIMD $EXC -O2 -Wno-everything -sUSE_FREETYPE=1 -I$SURGE/libs/JUCE/modules -include $GEN_DIR/AppConfig.h"

printf '%s\n' "${SOURCES[@]}" | xargs -P "$JOBS" -I{} bash -c '
    src="{}"
    obj="$OBJ_DIR/$(echo "${src#$REPO_ROOT/}" | tr "/" "_").o"
    if [ -f "$obj" ] && [ "$obj" -nt "$src" ]; then exit 0; fi
    # SheenBidi is C, not C++: -std=c++20 and the JUCE AppConfig force-include
    # would both be errors there.
    if [ "${src##*.}" = "c" ]; then
        if ! emcc $CFLAGS_STR -c "$src" -o "$obj" 2>"$obj.log"; then
            echo "FAILED: $src" >&2; tail -20 "$obj.log" >&2; exit 1
        fi
        printf "  %s\n" "$(basename "$src")"
        exit 0
    fi
    if ! em++ $CXXFLAGS_STR $DEFINES $INCLUDES -c "$src" -o "$obj" 2>"$obj.log"; then
        echo "FAILED: $src" >&2
        tail -20 "$obj.log" >&2
        exit 1
    fi
    printf "  %s\n" "$(basename "$src")"
' || die "One or more translation units failed to compile"

OBJS=()
for src in "${SOURCES[@]}"; do
    OBJS+=("$OBJ_DIR/$(echo "${src#"$REPO_ROOT"/}" | tr '/' '_').o")
done

# Every static archive the engine build produced.
mapfile -t ENGINE_LIBS < <(find "$ENGINE_BUILD" -name '*.a' | sort)

# EXPORT_ES6 is required, not cosmetic: MODULARIZE alone emits a UMD/CommonJS
# wrapper whose default export a browser dynamic import() cannot see, and the
# page dies with "createSurgeGui is not a function". ES6 output also resolves
# the .wasm against the module URL rather than the page root.
log "Linking ${#OBJS[@]} objects + ${#ENGINE_LIBS[@]} archives"
emcc "${OBJS[@]}" "${ENGINE_LIBS[@]}" \
    $SIMD $EXC -O2 \
    -sUSE_FREETYPE=1 \
    -o "$OUT" \
    -sMODULARIZE=1 \
    -sEXPORT_ES6=1 \
    -sEXPORT_NAME=createSurgeGui \
    -sENVIRONMENT=web \
    -sALLOW_MEMORY_GROWTH=1 \
    -sINITIAL_MEMORY=134217728 \
    -sSTACK_SIZE=4194304 \
    -sEXPORTED_RUNTIME_METHODS=cwrap,ccall,HEAPU8,HEAPF32,FS \
    -sEXPORTED_FUNCTIONS=_malloc,_free \
    -sASSERTIONS=1

[ -f "$OUT" ] || die "Link produced no output"
log "GUI: $(du -h "$OUT" | cut -f1) js + $(du -h "${OUT%.js}.wasm" | cut -f1) wasm"
