/**
 * keycodes.js -- browser KeyboardEvent.key -> juce::KeyPress code.
 *
 * GENERATED by tools/gen_keycodes.py -- edit that, not this. The C++ side
 * (host/surge_wasm/juce_KeyCodes_wasm.cpp) comes from the same table, so the
 * two cannot disagree. A mismatch would show up only as one particular key
 * silently doing nothing.
 */

export const JUCE_KEY_CODES = {
  " ": 32,
  "Escape": 27,
  "Enter": 13,
  "Tab": 9,
  "Backspace": 8,
  "Delete": 0x10000,
  "Insert": 0x10001,
  "ArrowUp": 0x10002,
  "ArrowDown": 0x10003,
  "ArrowLeft": 0x10004,
  "ArrowRight": 0x10005,
  "PageUp": 0x10006,
  "PageDown": 0x10007,
  "Home": 0x10008,
  "End": 0x10009,
  "F1": 0x1000a,
  "F2": 0x1000b,
  "F3": 0x1000c,
  "F4": 0x1000d,
  "F5": 0x1000e,
  "F6": 0x1000f,
  "F7": 0x10010,
  "F8": 0x10011,
  "F9": 0x10012,
  "F10": 0x10013,
  "F11": 0x10014,
  "F12": 0x10015,
  "F13": 0x10016,
  "F14": 0x10017,
  "F15": 0x10018,
  "F16": 0x10019,
  "F17": 0x1001a,
  "F18": 0x1001b,
  "F19": 0x1001c,
  "F20": 0x1001d,
  "F21": 0x1001e,
  "F22": 0x1001f,
  "F23": 0x10020,
  "F24": 0x10021,
};
