//==============================================================================
// KeyPress key codes.
//
// GENERATED by tools/gen_keycodes.py -- edit that, not this.
//
// JUCE declares these and leaves every platform to define them (Linux uses
// X11 keysyms, Windows uses VK_*). A browser has neither, so these values are
// ours: ASCII where a key has a natural one, otherwise a sequential id above
// 0x10000, clear of any Unicode codepoint. src/js/keycodes.js is generated
// from the same table so the two sides cannot drift apart.
//==============================================================================

namespace juce
{
const int KeyPress::spaceKey = 32;
const int KeyPress::escapeKey = 27;
const int KeyPress::returnKey = 13;
const int KeyPress::tabKey = 9;
const int KeyPress::backspaceKey = 8;
const int KeyPress::deleteKey = 0x10000;
const int KeyPress::insertKey = 0x10001;
const int KeyPress::upKey = 0x10002;
const int KeyPress::downKey = 0x10003;
const int KeyPress::leftKey = 0x10004;
const int KeyPress::rightKey = 0x10005;
const int KeyPress::pageUpKey = 0x10006;
const int KeyPress::pageDownKey = 0x10007;
const int KeyPress::homeKey = 0x10008;
const int KeyPress::endKey = 0x10009;
const int KeyPress::F1Key = 0x1000a;
const int KeyPress::F2Key = 0x1000b;
const int KeyPress::F3Key = 0x1000c;
const int KeyPress::F4Key = 0x1000d;
const int KeyPress::F5Key = 0x1000e;
const int KeyPress::F6Key = 0x1000f;
const int KeyPress::F7Key = 0x10010;
const int KeyPress::F8Key = 0x10011;
const int KeyPress::F9Key = 0x10012;
const int KeyPress::F10Key = 0x10013;
const int KeyPress::F11Key = 0x10014;
const int KeyPress::F12Key = 0x10015;
const int KeyPress::F13Key = 0x10016;
const int KeyPress::F14Key = 0x10017;
const int KeyPress::F15Key = 0x10018;
const int KeyPress::F16Key = 0x10019;
const int KeyPress::F17Key = 0x1001a;
const int KeyPress::F18Key = 0x1001b;
const int KeyPress::F19Key = 0x1001c;
const int KeyPress::F20Key = 0x1001d;
const int KeyPress::F21Key = 0x1001e;
const int KeyPress::F22Key = 0x1001f;
const int KeyPress::F23Key = 0x10020;
const int KeyPress::F24Key = 0x10021;
const int KeyPress::F25Key = 0x10022;
const int KeyPress::F26Key = 0x10023;
const int KeyPress::F27Key = 0x10024;
const int KeyPress::F28Key = 0x10025;
const int KeyPress::F29Key = 0x10026;
const int KeyPress::F30Key = 0x10027;
const int KeyPress::F31Key = 0x10028;
const int KeyPress::F32Key = 0x10029;
const int KeyPress::F33Key = 0x1002a;
const int KeyPress::F34Key = 0x1002b;
const int KeyPress::F35Key = 0x1002c;
const int KeyPress::numberPad0 = 0x1002d;
const int KeyPress::numberPad1 = 0x1002e;
const int KeyPress::numberPad2 = 0x1002f;
const int KeyPress::numberPad3 = 0x10030;
const int KeyPress::numberPad4 = 0x10031;
const int KeyPress::numberPad5 = 0x10032;
const int KeyPress::numberPad6 = 0x10033;
const int KeyPress::numberPad7 = 0x10034;
const int KeyPress::numberPad8 = 0x10035;
const int KeyPress::numberPad9 = 0x10036;
const int KeyPress::numberPadAdd = 0x10037;
const int KeyPress::numberPadSubtract = 0x10038;
const int KeyPress::numberPadMultiply = 0x10039;
const int KeyPress::numberPadDivide = 0x1003a;
const int KeyPress::numberPadSeparator = 0x1003b;
const int KeyPress::numberPadDecimalPoint = 0x1003c;
const int KeyPress::numberPadEquals = 0x1003d;
const int KeyPress::numberPadDelete = 0x1003e;
const int KeyPress::playKey = 0x1003f;
const int KeyPress::stopKey = 0x10040;
const int KeyPress::fastForwardKey = 0x10041;
const int KeyPress::rewindKey = 0x10042;
} // namespace juce
