/*
 * dump_layout.cpp -- emit Surge XT's GUI layout as JSON.
 *
 * WHY THIS EXISTS
 * ---------------
 * The browser GUI must place every control exactly where desktop Surge XT
 * places it. That layout lives in Surge's src/common/SkinModel.cpp as ~130
 * Connector definitions, e.g.
 *
 *     Connector("global.active_scene", 7, 12, 40, 42, Components::MultiSwitch)
 *     Connector("scene.volume", 0, 21).asHorizontal().asWhite()
 *                                     .inParent("scene.output.panel")
 *
 * Regex-parsing that C++ would be guesswork: coordinates are sometimes
 * parent-relative, style flags arrive through chained modifiers, and
 * properties are set via several different helpers (withHSwitch2Properties
 * expands to four separate properties, for one). Instead we link against
 * Surge's own SkinModel translation unit and ask its registry. The C++ stays
 * the single source of truth, and this stays correct when upstream moves.
 *
 * This is a build-time tool. It is native (not WASM) and is never shipped.
 *
 * Output: JSON on stdout. See tools/gen_layout.sh.
 */

#include "SkinModel.h"
#include "SurgeParamConfig.h"

#include <algorithm>
#include <iostream>
#include <map>
#include <sstream>
#include <string>
#include <vector>

using Surge::Skin::Component;
using Surge::Skin::Connector;

/*
 * Connector::NonParameterConnection identifies controls that do something
 * other than drive a parameter (the patch browser, the oscilloscope, undo...).
 * We emit the name rather than the raw ordinal so the layout stays readable
 * and does not silently shift meaning if upstream inserts an enumerator.
 */
#define NON_PARAM_CONNECTIONS(X)                                                                   \
    X(PARAMETER_CONNECTED)                                                                         \
    X(SURGE_MENU) X(OSCILLATOR_DISPLAY) X(OSCILLATOR_SELECT)                                       \
    X(JOG_PATCHCATEGORY) X(JOG_PATCH) X(JOG_FX) X(JOG_WAVESHAPE)                                   \
    X(ANALYZE_WAVESHAPE) X(ANALYZE_FILTERS)                                                        \
    X(SAVE_PATCH) X(SAVE_PATCH_DIALOG)                                                             \
    X(STATUS_MPE) X(STATUS_TUNE) X(STATUS_ZOOM)                                                    \
    X(ACTION_UNDO) X(ACTION_REDO)                                                                  \
    X(LFO_LABEL) X(FXPRESET_LABEL)                                                                 \
    X(PATCH_BROWSER) X(FX_SELECTOR) X(MAIN_VU_METER)                                               \
    X(MSEG_EDITOR_WINDOW) X(MSEG_EDITOR_OPEN) X(LFO_MENU)                                          \
    X(FILTER_ANALYSIS_WINDOW) X(OSCILLOSCOPE_WINDOW) X(WAVESHAPER_ANALYSIS_WINDOW)                 \
    X(FORMULA_EDITOR_WINDOW) X(WTS_EDITOR_WINDOW) X(TUNING_EDITOR_WINDOW)                          \
    X(MOD_LIST_WINDOW)

/* Pure function. Enum ordinal -> name, or "UNKNOWN_<n>" for unrecognized values. */
static std::string nonParamConnectionName(int n)
{
#define X(NAME)                                                                                    \
    if (n == Connector::NAME)                                                                      \
        return #NAME;
    NON_PARAM_CONNECTIONS(X)
#undef X
    return "UNKNOWN_" + std::to_string(n);
}

/* Pure function. Escapes a string for embedding in JSON. */
static std::string jsonEscape(const std::string &s)
{
    std::string out;
    for (char c : s)
    {
        switch (c)
        {
        case '"': out += "\\\""; break;
        case '\\': out += "\\\\"; break;
        case '\n': out += "\\n"; break;
        case '\r': out += "\\r"; break;
        case '\t': out += "\\t"; break;
        default: out += c;
        }
    }
    return out;
}

/*
 * Pure function. Renders a float as compact JSON.
 *
 * Surge stores positions as float but they are whole pixels in practice, so
 * printing 7 rather than 7.000000 keeps the layout file readable.
 */
static std::string num(float v)
{
    std::ostringstream o;
    if (v == static_cast<long long>(v))
        o << static_cast<long long>(v);
    else
        o << v;
    return o.str();
}

int main()
{
    auto ids = Connector::allConnectorIDs();
    std::sort(ids.begin(), ids.end());

    std::cout << "{\n";
    std::cout << "  \"_comment\": \"Generated by tools/dump_layout.cpp from Surge's "
                 "SkinModel.cpp. Do not edit by hand.\",\n";

    /* ---- component types (Slider, MultiSwitch, LFODisplay, ...) ---- */
    std::cout << "  \"components\": {\n";
    auto compIds = Component::allComponentIds();
    for (size_t i = 0; i < compIds.size(); ++i)
    {
        auto c = Component::componentById(compIds[i]);
        std::cout << "    \"" << compIds[i] << "\": {\"class\": \""
                  << jsonEscape(c.payload->internalClassname) << "\", \"aliases\": [";
        size_t k = 0;
        for (const auto &a : c.payload->aliases)
            std::cout << (k++ ? ", " : "") << "\"" << jsonEscape(a) << "\"";
        std::cout << "]}" << (i + 1 < compIds.size() ? "," : "") << "\n";
    }
    std::cout << "  },\n";

    /* ---- connectors: the actual control placements ---- */
    std::cout << "  \"connectors\": [\n";
    for (size_t i = 0; i < ids.size(); ++i)
    {
        auto c = Connector::connectorByID(ids[i]);
        auto &p = *c.payload;
        int f = p.controlStyleFlags;

        std::cout << "    {\n";
        std::cout << "      \"id\": \"" << jsonEscape(p.id) << "\",\n";
        std::cout << "      \"x\": " << num(p.posx) << ", \"y\": " << num(p.posy)
                  << ", \"w\": " << num(p.w) << ", \"h\": " << num(p.h) << ",\n";
        std::cout << "      \"component\": \""
                  << jsonEscape(p.defaultComponent.payload->internalClassname) << "\",\n";
        std::cout << "      \"componentId\": " << p.defaultComponent.payload->id << ",\n";
        std::cout << "      \"parent\": \"" << jsonEscape(p.parentId) << "\",\n";
        std::cout << "      \"nonParamConnection\": \""
                  << nonParamConnectionName(p.nonParamConnection) << "\",\n";
        std::cout << "      \"styleFlags\": " << f << ",\n";
        std::cout << "      \"style\": {"
                  << "\"vertical\": " << ((f & Surge::ParamConfig::kVertical) ? "true" : "false")
                  << ", \"horizontal\": "
                  << ((f & Surge::ParamConfig::kHorizontal) ? "true" : "false")
                  << ", \"white\": " << ((f & Surge::ParamConfig::kWhite) ? "true" : "false")
                  << "},\n";

        /* properties are an unordered_map; sort so the output is deterministic */
        std::map<std::string, std::string> props;
        for (const auto &kv : p.properties)
            props[Component::propertyEnumToString(kv.first)] = kv.second;

        std::cout << "      \"properties\": {";
        size_t k = 0;
        for (const auto &kv : props)
            std::cout << (k++ ? ", " : "") << "\"" << jsonEscape(kv.first) << "\": \""
                      << jsonEscape(kv.second) << "\"";
        std::cout << "}\n";
        std::cout << "    }" << (i + 1 < ids.size() ? "," : "") << "\n";
    }
    std::cout << "  ]\n}\n";

    std::cerr << "dump_layout: " << ids.size() << " connectors, " << compIds.size()
              << " component types\n";
    return 0;
}
