"""
Generate the KeyPress key-code definitions for the wasm ComponentPeer.

juce::KeyPress declares ~72 `static const int` key codes and leaves each
platform to define them (Linux uses X11 keysyms, Windows uses VK_*). A browser
has neither, so we choose our own values.

Scheme:
  - keys that have a natural ASCII code use it, so KeyPress(charCode) from a
    plain keypress matches: backspace 8, tab 9, return 13, escape 27, space 32
  - everything else gets a sequential id above 0x10000, which is where JUCE puts
    non-character keys by convention and safely clear of any Unicode codepoint

src/js/keycodes.js is generated from the SAME table so the browser side cannot
drift out of sync with the C++ side -- that mismatch would be invisible until a
particular key silently did nothing.
"""

from pathlib import Path

# JUCE name -> (value, browser KeyboardEvent.key). None means no browser key.
ASCII = {
    "spaceKey": (32, " "),
    "escapeKey": (27, "Escape"),
    "returnKey": (13, "Enter"),
    "tabKey": (9, "Tab"),
    "backspaceKey": (8, "Backspace"),
}

NAMED = [
    ("deleteKey", "Delete"),
    ("insertKey", "Insert"),
    ("upKey", "ArrowUp"),
    ("downKey", "ArrowDown"),
    ("leftKey", "ArrowLeft"),
    ("rightKey", "ArrowRight"),
    ("pageUpKey", "PageUp"),
    ("pageDownKey", "PageDown"),
    ("homeKey", "Home"),
    ("endKey", "End"),
]
NAMED += [(f"F{i}Key", f"F{i}" if i <= 24 else None) for i in range(1, 36)]
NAMED += [(f"numberPad{i}", None) for i in range(10)]
NAMED += [
    ("numberPadAdd", None),
    ("numberPadSubtract", None),
    ("numberPadMultiply", None),
    ("numberPadDivide", None),
    ("numberPadSeparator", None),
    ("numberPadDecimalPoint", None),
    ("numberPadEquals", None),
    ("numberPadDelete", None),
    ("playKey", None),
    ("stopKey", None),
    ("fastForwardKey", None),
    ("rewindKey", None),
]

BASE = 0x10000

cpp = [
    "//==============================================================================",
    "// KeyPress key codes.",
    "//",
    "// GENERATED by tools/gen_keycodes.py -- edit that, not this.",
    "//",
    "// JUCE declares these and leaves every platform to define them (Linux uses",
    "// X11 keysyms, Windows uses VK_*). A browser has neither, so these values are",
    "// ours: ASCII where a key has a natural one, otherwise a sequential id above",
    "// 0x10000, clear of any Unicode codepoint. src/js/keycodes.js is generated",
    "// from the same table so the two sides cannot drift apart.",
    "//==============================================================================",
    "",
    "namespace juce",
    "{",
]

js = [
    "/**",
    " * keycodes.js -- browser KeyboardEvent.key -> juce::KeyPress code.",
    " *",
    " * GENERATED by tools/gen_keycodes.py -- edit that, not this. The C++ side",
    " * (host/surge_wasm/juce_KeyCodes_wasm.cpp) comes from the same table, so the",
    " * two cannot disagree. A mismatch would show up only as one particular key",
    " * silently doing nothing.",
    " */",
    "",
    "export const JUCE_KEY_CODES = {",
]

for name, (val, browser) in ASCII.items():
    cpp.append(f"const int KeyPress::{name} = {val};")
    if browser:
        js.append(f"  {browser!r}: {val},".replace("'", '"'))

for i, (name, browser) in enumerate(NAMED):
    val = BASE + i
    cpp.append(f"const int KeyPress::{name} = 0x{val:05x};")
    if browser:
        js.append(f'  "{browser}": 0x{val:05x},')

cpp += ["} // namespace juce", ""]
js += ["};", ""]

Path("host/surge_wasm/juce_KeyCodes_wasm.cpp").write_text("\n".join(cpp))
Path("src/js/keycodes.js").write_text("\n".join(js))
print(f"wrote {len(ASCII) + len(NAMED)} key codes to C++ and JS")
