#!/usr/bin/env python3
"""
Generate SurgeXTBinary.{h,cpp}: Surge's fonts and skin assets embedded as C arrays.

WHY NOT JUST USE JUCE'S juce_add_binary_data?
---------------------------------------------
That CMake function runs `juceaide`, a NATIVE helper JUCE builds during
configure. Getting it to run in a cross-compile to WebAssembly means building a
second host toolchain inside the emscripten build, and the target only exists
inside src/surge-xt/CMakeLists.txt, which is skipped because we do not build the
JUCE plugin wrapper. Generating the same file directly is deterministic, has no
host-tool dependency, and is far easier to reason about.

The output matches the interface Surge actually consumes: a namespace with
`extern const char* name; const int nameSize;` per resource, plus
getNamedResource(). Verified against the symbols Surge references.

These resources are what make the GUI render correctly -- the Lato / IndieFlower
/ FiraMono typefaces and the classic skin SVGs. Without them Surge falls back to
whatever font it can find, which is exactly the "not the original GUI" failure.

Run:  uv run tools/gen_binary_data.py
"""

# /// script
# requires-python = ">=3.9"
# dependencies = ["fire"]
# ///

import re
import sys
from pathlib import Path

import fire

REPO_ROOT = Path(__file__).resolve().parent.parent
RESOURCES = REPO_ROOT / "vendor" / "surge" / "resources"
OUT_DIR = REPO_ROOT / "build" / "generated"

NAMESPACE = "SurgeXTBinary"

# Bytes per line in the generated arrays. Long enough to keep the file compact,
# short enough that compilers do not choke on the line length.
BYTES_PER_LINE = 32


def resource_files():
    """
    Query. The exact file set Surge's CMake embeds.

    Mirrors SURGE_XT_JUCE_RESOURCES_GLOB in src/surge-xt/CMakeLists.txt. Kept in
    the same order so the generated file is stable across runs.

    Returns:
        list[Path]

    Examples:
        >>> # any(p.name == 'Lato-Regular.ttf' for p in resource_files())
        >>> # True
    """
    files = []
    files += sorted((RESOURCES / "classic-skin-svgs").glob("*.svg"))
    files += sorted((RESOURCES / "fonts").glob("Lato*.ttf"))
    files += [RESOURCES / "fonts" / "IndieFlower.ttf"]
    files += [RESOURCES / "fonts" / "FiraMono-Regular.ttf"]
    files += [RESOURCES / "surge-xt" / "memory-skin.xml"]
    files += [RESOURCES / "surge-xt" / "wtfile_icon.svg"]
    files += [RESOURCES / "surge-xt" / "wtscript_icon.svg"]
    return files


def symbol_name(path):
    """
    Pure function. JUCE's mangling of a filename into a C identifier.

    JUCE strips non-alphanumeric characters but KEEPS underscores, and prefixes
    an underscore if the result would start with a digit. The underscore detail
    is easy to get wrong and shows up only as an unresolved symbol at link time:
    'wtscript_icon.svg' must become 'wtscript_icon_svg', not 'wtscripticon_svg'.

    Args:
        path (Path): the resource file

    Returns:
        str: the identifier

    Examples:
        >>> symbol_name(Path('Lato-Regular.ttf'))
        'LatoRegular_ttf'
        >>> symbol_name(Path('memory-skin.xml'))
        'memoryskin_xml'
        >>> symbol_name(Path('wtscript_icon.svg'))
        'wtscript_icon_svg'
        >>> symbol_name(Path('bmp00102.svg'))
        'bmp00102_svg'
    """
    stem = re.sub(r"[^a-zA-Z0-9_]", "", path.stem)
    ext = re.sub(r"[^a-zA-Z0-9_]", "", path.suffix)
    name = f"{stem}_{ext}"
    return f"_{name}" if name[0].isdigit() else name


def c_array(data):
    """
    Pure function. Renders bytes as the body of a C char array.

    Args:
        data (bytes)

    Returns:
        str

    Examples:
        >>> c_array(b'AB')
        '65,66'
    """
    out = []
    for i in range(0, len(data), BYTES_PER_LINE):
        chunk = data[i : i + BYTES_PER_LINE]
        out.append(",".join(str(b if b < 128 else b - 256) for b in chunk))
    return ",\n".join(out)


def main():
    """
    Command. Writes build/generated/SurgeXTBinary.{h,cpp}.

    Fails loudly on a missing resource: a silently absent font would show up
    only as subtly wrong text in the finished GUI.
    """
    files = resource_files()
    missing = [f for f in files if not f.is_file()]
    if missing:
        raise SystemExit(
            "Missing resources (run ./setup.sh first):\n  "
            + "\n  ".join(str(m) for m in missing)
        )

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    entries = [(symbol_name(f), f) for f in files]

    header = [
        "/* GENERATED by tools/gen_binary_data.py -- do not edit. */",
        "#pragma once",
        "",
        f"namespace {NAMESPACE}",
        "{",
    ]
    for sym, _ in entries:
        header.append(f"    extern const char*  {sym};")
        header.append(f"    const int           {sym}Size = 0;" if False else "")
    header = [h for h in header if h != ""]

    # Sizes must be real constants, not zero; emit them alongside the pointers.
    header = [
        "/* GENERATED by tools/gen_binary_data.py -- do not edit. */",
        "#pragma once",
        "",
        f"namespace {NAMESPACE}",
        "{",
    ]
    for sym, path in entries:
        header.append(f"    extern const char*  {sym};")
        header.append(f"    const int           {sym}Size = {path.stat().st_size};")
        header.append("")
    header += [
        "    // Number of elements in the namedResourceList array.",
        f"    const int namedResourceListSize = {len(entries)};",
        "",
        "    extern const char* namedResourceList[];",
        "    extern const char* originalFilenames[];",
        "",
        "    const char* getNamedResource (const char* resourceNameUTF8, int& dataSizeInBytes);",
        "}",
        "",
    ]

    source = [
        "/* GENERATED by tools/gen_binary_data.py -- do not edit. */",
        '#include "SurgeXTBinary.h"',
        "",
        "#include <cstring>",
        "",
        f"namespace {NAMESPACE}",
        "{",
    ]
    for sym, path in entries:
        data = path.read_bytes()
        source.append(f"// {path.name}")
        source.append(f"static const unsigned char temp_binary_data_{sym}[] = {{")
        source.append(c_array(data))
        source.append("};")
        source.append(
            f"const char* {sym} = (const char*) temp_binary_data_{sym};"
        )
        source.append("")

    source.append("const char* getNamedResource (const char* resourceNameUTF8, int& numBytes)")
    source.append("{")
    source.append("    unsigned int hash = 0;")
    source.append("    if (resourceNameUTF8 != nullptr)")
    source.append("        while (*resourceNameUTF8 != 0)")
    source.append("            hash = 31 * hash + (unsigned int) *resourceNameUTF8++;")
    source.append("")
    source.append("    switch (hash)")
    source.append("    {")
    seen = {}
    for sym, path in entries:
        h = 0
        for ch in sym.encode():
            h = (31 * h + ch) & 0xFFFFFFFF
        # A hash collision would silently return the wrong resource, so refuse
        # to emit a table that has one rather than shipping a subtle bug.
        if h in seen:
            raise SystemExit(f"Hash collision between {seen[h]} and {sym}")
        seen[h] = sym
        source.append(f"        case 0x{h:08x}:  numBytes = {path.stat().st_size}; return {sym};")
    source.append("        default: break;")
    source.append("    }")
    source.append("")
    source.append("    numBytes = 0;")
    source.append("    return nullptr;")
    source.append("}")
    source.append("")
    source.append("const char* namedResourceList[] =")
    source.append("{")
    for sym, _ in entries:
        source.append(f'    "{sym}",')
    source.append("};")
    source.append("")
    source.append("const char* originalFilenames[] =")
    source.append("{")
    for _, path in entries:
        source.append(f'    "{path.name}",')
    source.append("};")
    source.append("")
    source.append("}")
    source.append("")

    (OUT_DIR / "SurgeXTBinary.h").write_text("\n".join(header))
    (OUT_DIR / "SurgeXTBinary.cpp").write_text("\n".join(source))

    total = sum(p.stat().st_size for _, p in entries)
    print(f"Wrote {OUT_DIR.relative_to(REPO_ROOT)}/SurgeXTBinary.{{h,cpp}}")
    print(f"  {len(entries)} resources, {total / 1024:.0f} KiB of data")
    print(f"  fonts: {sum(1 for s, _ in entries if s.endswith('_ttf'))}")


if __name__ == "__main__":
    fire.Fire(main)
