#!/usr/bin/env bash
#
# Stage Surge's factory resources into src/data/ so the static site can serve them.
#
# Ships EVERYTHING Surge ships -- factory AND 3rd-party patches, wavetables and
# impulse responses (~480 MB). Per the user: "all their patches". The browser
# only fetches the index up front and lazy-loads individual patches, so page
# weight stays small; it is the repo that would grow, which is why src/data/ is
# gitignored and regenerated by this script from the pinned Surge SHA.
#
#   ./tools/stage_data.sh
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

SURGE_DATA="$REPO_ROOT/vendor/surge/resources/data"
DEST="$REPO_ROOT/src/data"

log() { printf '\033[1;36m==> %s\033[0m\n' "$*"; }
die() { printf '\033[1;31mERROR: %s\033[0m\n' "$*" >&2; exit 1; }

[ -d "$SURGE_DATA" ] || die "Surge resources not at '$SURGE_DATA'. Run ./setup.sh first."

# Surge resolves these by name under its data path, so the layout under src/data/
# must mirror resources/data/ exactly -- do not rename these directories.
BANKS=(
    patches_factory
    patches_3rdparty
    wavetables
    wavetables_3rdparty
    impulses_factory
    impulses_3rdparty
    fx_presets
    modulator_presets
    tuning_library
)

mkdir -p "$DEST"

for bank in "${BANKS[@]}"; do
    src="$SURGE_DATA/$bank"
    if [ ! -d "$src" ]; then
        # Loud, not silent: a missing bank means patches will fail to load later,
        # and a warning now is far cheaper to debug than a mystery later.
        printf '\033[1;33mWARNING: bank missing upstream, skipping: %s\033[0m\n' "$bank" >&2
        continue
    fi
    log "Staging $bank ($(du -sh "$src" | cut -f1))"
    # --delete so a re-run after an upstream bump does not leave orphans behind.
    rsync -a --delete "$src/" "$DEST/$bank/"
done

# configuration.xml and windows.wt are compiled into the wasm binary (Surge loads
# them "from memory"), so they are deliberately NOT staged here.

log "Staged $(du -sh "$DEST" | cut -f1) into ${DEST#"$REPO_ROOT"/}"
log "Patches: $(find "$DEST" -name '*.fxp' | wc -l)   Wavetables: $(find "$DEST" \( -name '*.wt' -o -name '*.wav' \) | wc -l)"
